site_name: BrowStyle

repo_name: "2024.1-Est-dio-de-Beleza-Keuany"
repo_url: "https://github.com/mdsreq-fga-unb/2024.1-Est-dio-de-Beleza-Keuany"

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: '#3dafe5'
      accent: '#3dafe5'
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: '#3dafe5'
      accent: '#3dafe5'


  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Introdução: index.md
  - Visão do Produto e Projeto:
    - Visão do Produto: visao_produto_projeto/visao_do_produto.md
    - Visão do Projeto: visao_produto_projeto/visao_do_projeto.md
  - Processo de Desenvolvimento de Software: processoDev.md 
  - Backlog:
    - Requisitos e Critérios: backlog/requisitos-criterios.md
    - MVP: backlog/mvp.md
  - Sprints:
    - Sprint 1: sprints/sprint-1.md
    - Sprint 2: sprints/sprint-2.md
  - Lições Aprendidas: licoesAprendidas.md
  - Entregas:
    - Unidade 1: entregas/unidade01.md
    - Unidade 2: entregas/unidade02.md